name: Catalyst-Plugin-Authentication-Store-LDAP
version: 0.03
abstract: Authenticate Users against LDAP Directories
author: Adam Jacob <holoway@cpan.org>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
requires:
  Net::LDAP: 0
  Catalyst::Plugin::Authentication: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.39
