---
abstract: 'Authenticate Users against LDAP Directories'
author:
  - 'Adam Jacob <holoway@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-Authentication-Store-LDAP
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Model::LDAP: 0
  Catalyst::Plugin::Authentication: 0.10002
  Net::LDAP: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.0602
