--- 
abstract: Authenticate Users against LDAP Directories
author: Adam Jacob <holoway@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Plugin-Authentication-Store-LDAP
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Model::LDAP: 0
  Catalyst::Plugin::Authentication: 0
  Net::LDAP: 0
version: 0.0600
